name: Flutter Web Deploy (main branch /docs)

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3' # Replace with your Flutter version
          channel: 'stable'

      - run: flutter pub get
      - run: flutter build web --release --base-href "/${{ github.event.repository.name }}/"

      - name: Move build to docs folder
        run: |
          rm -rf docs
          mkdir docs
          cp -r build/web/* docs/

      - name: Commit docs folder
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Update docs folder for GitHub Pages" || echo "No changes to commit"
          git push
